name: Actualizar Memoria del Proyecto

on:
  push:
    branches:
      - main

jobs:
  actualizar-memoria:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Instalar rclone
      run: |
        sudo apt-get update
        sudo apt-get install -y rclone

    - name: Configurar y sincronizar con rclone
      env:
        RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
      run: |
        rclone sync ./docs remote:Proyecto/backup
